---
title: "Chapter 2"
subtitle: "Crawl first, Walk next, Run later"
description: "Word Count: 4378"
format: html
project-type: book
---

____

What is living a "normal" life like?

Kratos pondered on that thought quite a bit, nowadays, given how he was afforded an endless amount of time to just linger on his thoughts. Gone were the days where he had to wake up before the crack of dawn and cycle through the daily drills. He was also no longer required to brood over the next tasks handed to him by the gods. Finally, he also didn't need to plot his vengeance. That was a massive chip off his shoulder. He could now life out the so-called "normal" life that everyone kept talking about.

But did he even deserve to live a "normal" life, after all he'd done?

That was always the question that followed the first. From a purely Spartan perspective, it should be his rightful prize. After all, all that matters in any war is the winner, and Kratos (for all intents and purposes) won. The gods that wronged him were dead. The world that glorified said dieties was reduced to ruins. Kratos won.

But what did he win?

The result of any war should be peace, right? But Kratos wasn't in peace. In fact, his psyche constantly danced on the precarious edge of a blade. A blade that, metaphorically, loomed over his neck and threatened to cleft it in two at a moment's notice.

Kratos wondered if this was why Spartan warriors were forced to go through gruelling and torturous training every day, even if there was no war in the horizon. Because when left to their thoughts, they were forced to live the horrors they had to commit in the name of their land. Because most humans are born with a conscience, and one's conscience tends to be their harshest critique. Because the conscience tends to veer towards committing suicide when there was no way out of the guilt that consumed you, after realising that there was just not enough soap in the world to wash away the blood that caked your ruinous hands.

It amused him to realise that he was ultimately turning into an Athenian pansy. All they did was waste away their days pondering over useless drivel, like what is right and what is wrong, or why the human mind worked the way it did. A Spartan's purpose is to *do*, not *question*.

But there WAS nothing left for Kratos to *do*. So what was his purpose?

According to the long-haired man, who had brought him back from the warm embrace of Hades (if that even existed anymore), Kratos' current purpose was to learn the language spoken by the people of the land he now walked.

On that note, Kratos learned quite a bit about his current position. For one, the world he was in was called "Bharat". Upon questioning of the existence of his homeworld, Greece, Kratos was told that it probably existed somewhere westwards, beyond the fields and oceans of chaos that separated the planes. There were words of Greek artefacts owned by rulers or powerful clans in these lands, and they were rumoured to have been brought over by adventurous traders who sought luck and fortune by crossing through the chaos.

The source of all this information, of course, was the long-haired man who was also his language teacher. The man's name was Rama Bhargava, not a name or root that Kratos was familiar with (which further drove in the point that he was no longer in familiar lands).

"To make this sound, you need to aspirate while making the same 'k' sound," Rama explained while pointing at a letter that looked like घ.

Kratos growled irritatedly and barked, "That's how I pronounced it!"

"You aren't releasing air hard enough. If you don't do that, it will sound like ग," Rama responded while shaking his head. "It's been over two weeks, Kratos. I expected faster progress. We've barely scratched the surface, you still have two other sets of alphabets to go through."

"Why are there so many languages?" Kratos exclaimed in frustration. "Where I come from, everyone spoke just one."

"What does language mean to you?" Rama inquired, while placing the square cutting of slate with the chalk letter written on it aside.

"It is a means of communication," Kratos responded. "Which means that one is enough."

"Communication has different orders," Rama corrected. "The way you communicate with your family may differ from the way you communicate with your friends. The way you communicate with your child may differ from the way you communicate with your superiors. Language changes when the person you are speaking to changes, because what you want to convey changes and so does the way you want to convey it. Language changes when culture changes, because what you share most often differs if the life you live differs. The words and phrases a kind may use amongst his ministers is vastly different from the language used by the lowly peasant as he communicates with his neighbour."

"You talk alot," Kratos interjected as Rama took a break to let his words settle.

"It's because you are a great listener," Rama said with a chuckle. "In fact, I used two different languages in my previous 'rant'."

"Why?" Kratos probed.

"You know this is the first time you've ever asked that question," Rama pointed out. "Why? What a great word it is. Many men more learned than I have said that it is one of the most dangerous phrases out there, because it cuts right to the core of everything. The cause!"

"Answer my question!" Kratos growled angrily.

"Fine, fine," Rama said. "No patience at all."

"People are born with purpose. A warrior's purpose is to fight for a cause he follows and die in teh battle field. A merchant's purpose is to trade and generate wealth. A peasant's purpose is to till the earth and grow crops. And a priest's purpose is to perform religious rites, preserve knowledge, and guide the development of civilisation as a whole. To that end, there are topics of discussion that are common amongst one caste that aren't encroached upon by the other. So there isn't a need for someone in, let's say, the Kshatriya (the warrior or ruler) caste to discuss with the Vaishya (merchant or trader) caste. Hence there isn't a need for the Vaishyas to have a language that spans contexts ranging over discussions of statecraft, warfare and politic," Rama explained.

"So why are you teaching me all three languages?" Kratos probed. "I don't intend to communicate with rulers or ply myself in politics."

"How do you know your purpose?" Rama responded. "You weren't born here, thus you don't have a caste, and so your purpose in life is fairly open."

"Who decides my purpose," Kratos murmured.

"If you were part of our cycle of reincarnation," Rama said while raising his arms towards the sky, "Then the world itself decides for you. But since that isn't the case here, well, I guess you are free to decide what your purpose in life is supposed to be."

"The language I'm teaching you right now is called Sanskrit," Rama continued as he pulled back the slate board. "It is said to be the language spoken by the world itself. It is said that if you can formulate a prose so profound in Sanskrit, the world will respond in kind. The script I am teaching you is just the surface. The beauty of the language runs deep. I'm afraid even I cannot teach you all about it."

"So why don't we start simpler?"

"Because all other languages begin from this. This and Tamil, which is the other language I will teach you," Rama emphasised while raising two fingers.

Kratos growled with a low rumble as he thought of the arduous exercise before him. "All this knowlege is wasted on me."

"Poppycock!" The man snapped back. "Knowledge is never wasted. The more it is distributed, the more it grows."

He then pointed at the rustling leaves of a tree nearby, and gently gestured for it to come closer. Then, from within the branches, an apple floated towards him.

"Knowledge is like this fruit here. It is juicy and sweet, filled with good stuff. But amidst all the fleshy goodness lies a seed-" with a quick pull, the apple was broken in two revealing the seeds within. "Now, the apple that remains on the tree, withers and dies. But the apple that is eaten by the common pigeon manages to have its seed carried with the bird as the creature flies away. As the creature defacates, the seed is planted. In the faeces, it finds sustenance. And once the heavens grace the seed with nurturing rain, a new tree grows in its place."

He pointed at Kratos and revealed a mischeavous smile, "In our case, I am the tree. The apple is my knowledge. You are the bird. So fly! Oh, great bird! Defacate where your heart calls you and spread the beauty far and wide."

"You are a weird man," Kratos commented. "We will talk no more. Continue your lesson now."

In turn, the man let out an uproarious laught and continued writing and sounding out the letters.

____

"Two. Apples." Kratos said to the panicking vendor standing behind his mobile stall.

"#%!%$& apples are, one cowrie shell each," the man answered while raising two shivering fingers. Kratos let out a growl before producing the shells to complete the transaction. He then accepted the offered fruits and bit into one. A faint, satisfied smile caused the corner of lips to quirk upwards slightly as a thin trace of juice dripped down the side of his lips.

Kratos missed the minor joys in life. Even a simple treat like an apple could tickle his senses to such a degree that 

Kratos living with with long haired man who he finds out is called Rama Bhargava. Describe his daily life.

Kratos learning the languages: Sanskrit and Common Dialects and Derivations.

Struggling with his inner urge to kill himself and continue living. Conversation with Rama to come to terms with that.

Comment on Rama never sleeping and only relying on meditation to pass the time. Kratos' opinion on meditation.

One time Rama falls asleep while meditating --> ends in a fight between Kratos and Rama while the latter is sleeping.
